import turtle
turtle.pensize(10)
turtle.color("red")
turtle.circle(100)
turtle.penup()
turtle.goto(0,90)
turtle.pendown()
turtle.color("black")
turtle.pensize(4)
turtle.left(45)
turtle.forward(75)
turtle.goto(0,90)
turtle.pendown()
turtle.pensize(7)
turtle.right(135)
turtle.forward(70)
turtle.penup()
turtle.goto(-5,95)
turtle.pendown()
turtle.color("yellow")
turtle.fillcolor("yellow")
turtle.begin_fill()
turtle.circle(10)
turtle.end_fill()
turtle.hideturtle()

